Support gymnasium 1.0
Toni-SM/skrl pull request #212
Opened 2024-10-15 15:46 UTC by Jendker

This adds changes required to support gymnasium 1.0.
Tested with PPO and observed no regression in the learning quality and performance.

Please let me know if you have any suggestions.

2024-10-15 15:51 UTC, Jendker commented
Since `make_vec` defaults to sync mode as per docs: https://github.com/Farama-Foundation/Gymnasium/blob/d571ed63017fb0bf1a9022960a3798b8d7c8b409/gymnasium/envs/registration.py#L849-L851 I have removed the synchronous argument from `make_vec`.

2025-01-07 04:23 UTC, Toni-SM requested changes

2025-01-07 04:23 UTC, Toni-SM commented on docs/source/snippets/wrapping.py
> +env = gym.make_vec("Pendulum-v1", num_envs=10)
`make_vec` is only a Gymnasium 1.0 feature... so, the modification does not apply for Gym-based code and examples

2025-01-07 04:23 UTC, Toni-SM commented on docs/source/snippets/wrapping.py
> -env = gym.vector.make("Pendulum-v1", num_envs=10, asynchronous=False)
`make_vec` is only available in Gymnasium >= 1.0. 
I would keep a note for previous Gymnasium versions instead of just delete it.

2025-01-07 23:00 UTC, Jendker commented on docs/source/snippets/wrapping.py
> +env = gym.make_vec("Pendulum-v1", num_envs=10)
Good point. Any suggestions on how to make this backward-compatible?

2025-01-09 13:24 UTC, closed without merging